version: 1.0.{build}
skip_tags: true
build:
  publish_wap: true
  verbosity: minimal
deploy:
- provider: WebDeploy
  server: https://html2markdown.scm.azurewebsites.net:443/msdeploy.axd?site=Html2Markdown
  website: Html2Markdown
  username: $Html2Markdown
  password:
    secure: JGEG+D6uyaIvly11Hlj8r3HH92NyYddQZbdT8ykwueI1y/m5FRJ/oOuVqa56tWLI0ApLNsfkvmDaizIku3MvvA==
  on:
    branch: master
notifications:
  - provider: Slack
    auth_token:
      secure: xLrYwFJVzehV+sdSJsDp52X1TSPeSGJrr56LI2GQDvrmkpjcrwX1rmPwdH+i14H8lijQDcWbUt9jl81saehgRA==
    channel: '#build'